[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:apache2]
command=/bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"
autostart=true
autorestart=true
stdout_logfile=/var/log/apache2/out.log
stderr_logfile=/var/log/apache2/err.log

[program:vsftpd]
# Forzamos la creación del directorio necesario para chroot antes de lanzar vsftpd
command=/bin/bash -c "mkdir -p /var/run/vsftpd/empty && exec /usr/sbin/vsftpd /etc/vsftpd.conf"
autostart=true
autorestart=true
stdout_logfile=/var/log/vsftpd.log
stderr_logfile=/var/log/vsftpd.log

[program:rsyslog]
command=/usr/sbin/rsyslogd -n
autostart=true
autorestart=true
