-- ==========================================================
-- PROYECTO FINAL: GESTIÓN DE INVENTARIO DE INFRAESTRUCTURA
-- AUTOR: ÁLVARO REMIS BUSTO | ID: 242V
-- SCRIPT DE CREACIÓN DE BASES DE DATOS CON LENGUAJE DDL
-- ==========================================================
-- ----------------------------------------------------------
-- TABLA DE PARÁMETROS BÁSICOS
-- ----------------------------------------------------------

CREATE TABLE PARAMETROS_BASICOS (
    PARAMETRO VARCHAR2(100) PRIMARY KEY,
    VALOR     VARCHAR2(255) NOT NULL
);

-- ----------------------------------------------------------
-- TABLA DE REDES
-- ----------------------------------------------------------

CREATE TABLE REDES (
    ID_RED           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE_RED       VARCHAR2(50) NOT NULL UNIQUE,
    DIRECCION_RED    VARCHAR2(50) NOT NULL,
    GATEWAY          VARCHAR2(50),
    INTERFAZ_ROUTER  VARCHAR2(20),
    DESCRIPCION      VARCHAR2(500)
);

-- ----------------------------------------------------------
-- TABLA DE SISTEMAS OPERATIVOS
-- ----------------------------------------------------------

CREATE TABLE SISTEMAS_OPERATIVOS (
    ID_SO   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE  VARCHAR2(100) NOT NULL,
    VERSION VARCHAR2(100),
    CONSTRAINT UQ_SO UNIQUE (NOMBRE, VERSION)
);

-- ----------------------------------------------------------
-- TABLA DE SERVICIOS
-- ----------------------------------------------------------

CREATE TABLE SERVICIOS (
    ID_SERVICIO     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE_SERVICIO VARCHAR2(100) NOT NULL UNIQUE
);

-- ----------------------------------------------------------
-- TABLA DE EQUIPOS
-- ----------------------------------------------------------

CREATE TABLE EQUIPOS (
    ID_EQUIPO         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HOSTNAME          VARCHAR2(100) NOT NULL UNIQUE,
    DOMINIO           VARCHAR2(100),
    FUNCION_PRINCIPAL VARCHAR2(255),
    IP_PRIMARIA       VARCHAR2(50),
    MAC_PRIMARIA      VARCHAR2(50),
    ID_RED            NUMBER,
    ID_SO             NUMBER,
    CONSTRAINT FK_EQ_RED FOREIGN KEY (ID_RED) REFERENCES REDES(ID_RED),
    CONSTRAINT FK_EQ_SO  FOREIGN KEY (ID_SO)  REFERENCES SISTEMAS_OPERATIVOS(ID_SO)
);

-- ----------------------------------------------------------
-- TABLA DE HARDWARE
-- ----------------------------------------------------------

CREATE TABLE EQUIPO_HARDWARE (
    ID_HARDWARE      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_EQUIPO        NUMBER NOT NULL,
    TIPO_COMPONENTE  VARCHAR2(50) CHECK (TIPO_COMPONENTE IN ('CPU', 'RAM', 'DISCO')),
    CANTIDAD         NUMBER DEFAULT 1,
    CAPACIDAD        VARCHAR2(50),
    DETALLES         VARCHAR2(500),
    CONSTRAINT FK_HW_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO)
);

CREATE TABLE USUARIOS_CREDENCIALES (
    ID_CREDENCIAL NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AMBITO        VARCHAR2(100), 
    USUARIO       VARCHAR2(100) NOT NULL,
    PASSWORD_HASH VARCHAR2(255),
    ID_EQUIPO     NUMBER, 
    CONSTRAINT FK_USR_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO)
);

CREATE TABLE EQUIPO_SERVICIO (
    ID_EQUIPO   NUMBER NOT NULL,
    ID_SERVICIO NUMBER NOT NULL,
    CONSTRAINT PK_EQ_SERV PRIMARY KEY (ID_EQUIPO, ID_SERVICIO),
    CONSTRAINT FK_ES_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT FK_ES_SERV   FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIOS(ID_SERVICIO)
);


-- ----------------------------------------------------------
-- Para dar sentido y uniformidad a la creación de tablas se ha decidido utilizar IDs númericos como claves primarias. Dichos IDs se incrementan al añadir datos
-- nuevos con la funcion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY de Oracle. Los valores que no debían ser nulos se han definido con NOT NULL y con
-- NOT NULL UNIQUE si se ha considerado que los valores no deben repetirse. Se han creado limitadores a la hora de introducir valores de componentes de Hardware
-- con la función CHECK (TIPO_COMPONENTE IN ('CPU', 'RAM', 'DISCO')), de tal forma que si el tipo de componente no es uno de esos 3 el dato no se introducirá en
-- la tabla. Finalmente, se han definido claves foráneass que conectan todas las tablas entre sí. La función utilizada tiene esta estructura:
--     CONSTRAINT FK_USR_EQUIPO FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO)
-- Esa sentencia hace que no se puedan introducir datos (CONSTRAINT), se le da un nombre a la regla (FK_USR_EQUIPO), se define la clave foránea (FOREIGN KEY())
-- y se dice que es lo que referencia con REFERENCES TABLA(COLUMNA). Con el uso de estas sentencias hacemos que la tabla EQUIPOS se conecte con las tablas 
-- REDES y SISTEMAS_OPERATIVOS a través de las claves foráneas id_red y id_so, que la tabla EQUIPO_HARDWARE se conecte con EQUIPOS a través de la FK id_equipo.
-- que la tabla USUARIOS_CREDENCIALES esté conectada con la tabla equipos y que la tabla EQUIPO_SERVICIO se conecte con las tabls equipos y servicios. De esta
-- forma conseguimos unir datos de cada equipo con datos de red, servicios, usuarios y hardware, normalizando la distribución de la información y permitiendo
-- realizar consultas complejas que nos devuelvan toda la información necesaria.
-- ----------------------------------------------------------