-- ==========================================================
-- PROYECTO FINAL: GESTIÓN DE INVENTARIO DE INFRAESTRUCTURA
-- AUTOR: ÁLVARO REMIS BUSTO | ID: 242V
-- SCRIPT DE CREACIÓN DE BASES DE DATOS CON LENGUAJE DML
-- ==========================================================

-- 1:ROUTER, 2:LAMP, 3:DC01, 4:DC02, 5:FILER, 6:WS01, 7:WS02, 8:WS03, 9:EXTERNA, 10:HV01, 11:HV02, 12:VCENTER

-- Con esta sentencia nos aseguramos de que no habra problemas de inserción con los $ de las contraseñas
SET DEFINE OFF;

-- ----------------------------------------------------------
-- 1. PARÁMETROS BÁSICOS
-- ----------------------------------------------------------
INSERT INTO PARAMETROS_BASICOS VALUES ('Alumno', 'Álvaro Remis Busto');
INSERT INTO PARAMETROS_BASICOS VALUES ('AlumnoAD', 'alvaro');
INSERT INTO PARAMETROS_BASICOS VALUES ('Puesto de clase', '24');
INSERT INTO PARAMETROS_BASICOS VALUES ('ID de proyecto', '242V');
INSERT INTO PARAMETROS_BASICOS VALUES ('Servidor de virtualización', 'VIRTUA31');
INSERT INTO PARAMETROS_BASICOS VALUES ('Grupo en el servidor', '9');
INSERT INTO PARAMETROS_BASICOS VALUES ('Nombre de dominio AD', 'asi-242V.cifpaviles.com');
INSERT INTO PARAMETROS_BASICOS VALUES ('Nombre de dominio NETBIOS', 'ASI-242V');
INSERT INTO PARAMETROS_BASICOS VALUES ('Nombre de reino kerberos', 'ASI-242V.CIFPAVILES.COM');

-- ----------------------------------------------------------
-- 2. REDES
-- ----------------------------------------------------------
INSERT INTO REDES (NOMBRE_RED, DIRECCION_RED, GATEWAY, INTERFAZ_ROUTER) VALUES ('EXTERNA', '10.31.9.0/24', '10.31.9.254', 'eth0');
INSERT INTO REDES (NOMBRE_RED, DIRECCION_RED, GATEWAY, INTERFAZ_ROUTER) VALUES ('DMZ', '172.16.24.0/24', '172.16.24.1', 'eth1');
INSERT INTO REDES (NOMBRE_RED, DIRECCION_RED, GATEWAY, INTERFAZ_ROUTER) VALUES ('SERVIDORES INTERNOS', '172.20.24.0/24', '172.20.24.1', 'eth2');
INSERT INTO REDES (NOMBRE_RED, DIRECCION_RED, GATEWAY, INTERFAZ_ROUTER) VALUES ('GESTION', '172.24.24.0/24', '172.24.24.1', 'eth3');
INSERT INTO REDES (NOMBRE_RED, DIRECCION_RED, GATEWAY, INTERFAZ_ROUTER) VALUES ('ESTACIONES', '172.28.24.0/24', '172.28.24.1', 'eth4');
INSERT INTO REDES (NOMBRE_RED, DIRECCION_RED, GATEWAY, INTERFAZ_ROUTER) VALUES ('VPN', '172.31.24.0/24', '172.31.24.1', 'tun0');

-- ----------------------------------------------------------
-- 3. SISTEMAS OPERATIVOS
-- ----------------------------------------------------------
INSERT INTO SISTEMAS_OPERATIVOS (NOMBRE, VERSION) VALUES ('Zentyal', '6.2');
INSERT INTO SISTEMAS_OPERATIVOS (NOMBRE, VERSION) VALUES ('Ubuntu Server', '24.04 LTS');
INSERT INTO SISTEMAS_OPERATIVOS (NOMBRE, VERSION) VALUES ('Windows Server', '2022');
INSERT INTO SISTEMAS_OPERATIVOS (NOMBRE, VERSION) VALUES ('TrueNAS', 'Core');
INSERT INTO SISTEMAS_OPERATIVOS (NOMBRE, VERSION) VALUES ('Windows 10', 'Pro');
INSERT INTO SISTEMAS_OPERATIVOS (NOMBRE, VERSION) VALUES ('Windows 11', 'Pro');
INSERT INTO SISTEMAS_OPERATIVOS (NOMBRE, VERSION) VALUES ('Ubuntu Desktop', '24');
INSERT INTO SISTEMAS_OPERATIVOS (NOMBRE, VERSION) VALUES ('ESXi', '8.0');

-- ----------------------------------------------------------
-- 4. SERVICIOS
-- ----------------------------------------------------------
INSERT INTO SERVICIOS (NOMBRE_SERVICIO) VALUES ('Apache2');
INSERT INTO SERVICIOS (NOMBRE_SERVICIO) VALUES ('MySQL/MariaDB');
INSERT INTO SERVICIOS (NOMBRE_SERVICIO) VALUES ('Active Directory');
INSERT INTO SERVICIOS (NOMBRE_SERVICIO) VALUES ('DNS');
INSERT INTO SERVICIOS (NOMBRE_SERVICIO) VALUES ('DHCP');
INSERT INTO SERVICIOS (NOMBRE_SERVICIO) VALUES ('OpenVPN');
INSERT INTO SERVICIOS (NOMBRE_SERVICIO) VALUES ('SMB/NFS');
INSERT INTO SERVICIOS (NOMBRE_SERVICIO) VALUES ('VCSA');

-- ----------------------------------------------------------
-- 5. EQUIPOS (Referenciando IDs de Red y SO)
-- ----------------------------------------------------------
INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('ROUTER01-242V', 'WORKGROUP', 'Router Frontera', '10.31.9.254', '00:50:56:be:76:3b', 1, 1);

INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('LAMP01-242V', 'WORKGROUP', 'Servidor Web', '172.16.24.77', '00:50:56:be:d1:eb', 2, 2);

INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('DC01-242V', 'asi-242V.cifpaviles.com', 'DC Primario', '172.20.24.10', '00:50:56:be:4b:26', 3, 3);

INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('DC02-242V', 'asi-242V.cifpaviles.com', 'DC Secundario', '172.20.24.11', '00:50:56:be:2e:5c', 3, 3);

INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('FILER01-242V', 'asi-242V.cifpaviles.com', 'Servidor Archivos', '172.24.24.11', '00:50:56:be:d1:eb', 4, 4);

INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('WS01-242V', 'asi-242V.cifpaviles.com', 'Estación Win10', '172.28.24.10', '00:50:56:be:fd:d1', 5, 5);

INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('WS02-242V', 'asi-242V.cifpaviles.com', 'Estación Win11', '172.28.24.11', '00:50:56:be:e8:1c', 5, 6);

INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('WS03-242V', 'asi-242V.cifpaviles.com', 'Estación Linux', '172.28.24.24', '00:50:56:be:ad:cf', 5, 7);

INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('EXTERNA01-242V', 'WORKGROUP', 'PC Externo', '10.31.9.20', '00:50:56:be:c3:21', 1, 6);

INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('HV01-242V', 'WORKGROUP', 'Hipervisor 1', '172.24.24.31', '00:50:56:be:9a:12', 4, 8);

INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('HV02-242V', 'WORKGROUP', 'Hipervisor 2', '172.24.24.32', '00:50:56:be:54:33', 4, 8);

INSERT INTO EQUIPOS (HOSTNAME, DOMINIO, FUNCION_PRINCIPAL, IP_PRIMARIA, MAC_PRIMARIA, ID_RED, ID_SO) 
VALUES ('VCENTER01-242V', 'asi-242V.cifpaviles.com', 'VCSA', '172.24.24.100', '00:50:56:be:11:22', 4, 3);

-- ----------------------------------------------------------
-- 2. HARDWARE
-- ----------------------------------------------------------
-- ROUTER01
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (1, 'CPU', 2, NULL);
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (1, 'RAM', 1, '2GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (1, 'DISCO', 1, '25GB');
-- LAMP01
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (2, 'CPU', 1, NULL, '1 vCPU');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (2, 'RAM', 1, '4GB', 'DDR4');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (2, 'DISCO', 2, '55GB', 'RAID 1 (SO)');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (2, 'DISCO', 3, '10GB', 'RAID 5 (MySQL)');
-- DC01
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (3, 'CPU', 1, NULL);
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (3, 'RAM', 1, '3GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (3, 'DISCO', 1, '40GB', 'Disco 1');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (3, 'DISCO', 1, '10GB', 'Disco 2');
-- DC02
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (4, 'CPU', 2, NULL);
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (4, 'RAM', 1, '3GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (4, 'DISCO', 2, '40GB', 'RAID 1');
-- FILER01
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (5, 'CPU', 1, NULL);
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (5, 'RAM', 1, '2GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (5, 'DISCO', 1, '16GB', 'Disco 1');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (5, 'DISCO', 1, '50GB', 'Disco 2');
-- ESTACIONES (WS01, WS02, WS03)
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (6, 'CPU', 1, NULL);
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (6, 'RAM', 1, '3GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (6, 'DISCO', 1, '40GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (7, 'CPU', 2, NULL);
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (7, 'RAM', 1, '4GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (7, 'DISCO', 1, '52GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (8, 'CPU', 1, NULL);
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (8, 'RAM', 1, '2GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (8, 'DISCO', 1, '50GB', 'Disco 1');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (8, 'DISCO', 1, '10GB', 'Disco 2');
-- EXTERNA01
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (9, 'CPU', 1, NULL);
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (9, 'RAM', 1, '3GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (9, 'DISCO', 1, '40GB');
-- HV01 y HV02 (Hipervisores)
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (10, 'CPU', 2, NULL);
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (10, 'RAM', 1, '10.01GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (10, 'DISCO', 1, '20GB', 'Boot');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (10, 'DISCO', 2, '50GB', 'Datastores');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (11, 'CPU', 2, NULL);
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD) VALUES (11, 'RAM', 1, '4GB');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (11, 'DISCO', 1, '20GB', 'Boot');
INSERT INTO EQUIPO_HARDWARE (ID_EQUIPO, TIPO_COMPONENTE, CANTIDAD, CAPACIDAD, DETALLES) VALUES (11, 'DISCO', 2, '50GB', 'Datastores');

-- --------------------------------------------------------------------------------------
-- 3. CREDENCIALES (Las hasheamos con la funcion STANDARD_HASH('contraseña', 'formato')
-- --------------------------------------------------------------------------------------
-- Credenciales de administradores locales
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Local Admin', 'administrador', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 2); 
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Local Admin', 'administrador', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 1); 
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Local Admin', 'administrador', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 8); 

-- Usuarios de Dominio (ASI-242V)
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'Administrator', STANDARD_HASH('Moreniko$hikitico', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'alvaro', STANDARD_HASH('Temporal242v!', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'manuel', STANDARD_HASH('Temporal242v!', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'manu', STANDARD_HASH('Temporal242v!', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'andres', STANDARD_HASH('Temporal242v!', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'victor', STANDARD_HASH('Temporal242v!', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'toni', STANDARD_HASH('Temporal242v!', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'luisma', STANDARD_HASH('Temporal242v!', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'guillermo', STANDARD_HASH('Temporal242v!', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'ruben', STANDARD_HASH('Temporal242v!', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'luis', STANDARD_HASH('Temporal242v!', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('ASI-242V', 'olga', STANDARD_HASH('Temporal242v!', 'SHA256'));

-- Otros Servicios (BBDD y FTP)
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Moodle FTP', 'administrador', STANDARD_HASH('administrador', 'SHA256'), 2);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Wordpress FTP', 'administrador', STANDARD_HASH('administrador', 'SHA256'), 2);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Inventario FTP', 'administrador', STANDARD_HASH('administrador', 'SHA256'), 2);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Default FTP', 'administrador', STANDARD_HASH('administrador', 'SHA256'), 2);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('NPM', 'administrador', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 2);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Moodle Admin Web', 'admin', STANDARD_HASH('Moreniko$hikitico1', 'SHA256'), 2);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Wordpress Admin Web', 'admin', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 2);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Moodle ROOT DB', 'root', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 2);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Wordpress ROOT DB', 'root', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 2);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Moodle MariaDB', 'moodleuser', STANDARD_HASH('moodlepass', 'SHA256'), 2);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('Oracle Inventario', 'alvaro.oracle', STANDARD_HASH('1234', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('MySQL Wordpress', 'wordpressuser', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 2);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH) VALUES ('Oracle ROOT DB', 'root', STANDARD_HASH('1234', 'SHA256'));
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('VCSA SSO', 'Administrator@vsphere.local', STANDARD_HASH('Tr0p!cal#26', 'SHA256'), 12);


-- DSRM de los Controladores de Dominio
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('DSRM DC01', 'DSRM1', STANDARD_HASH('E3@7xJ7a)89]', 'SHA256'), 3);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('DSRM DC02', 'DSRM2', STANDARD_HASH('E3@7xJ7a)89]', 'SHA256'), 4);

-- Contraseñas locales
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('DC01-242V', '.\Administrator', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 3);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('DC02-242V', '.\Administrator', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 4);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('Hipervisor ROOT', 'root', STANDARD_HASH('Moreniko$hikitico2026', 'SHA256'), 10);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('VCSA ROOT', 'root', STANDARD_HASH('Tr0p!cal#26', 'SHA256'), 12);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('WS01-242V', '.\admin', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 6);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('WS02-242V', '.\admin', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 7);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('WS03-242V', 'root', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 8);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('WS03-242V', '/dev/sdb', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 8);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('HV01-242V', 'root', STANDARD_HASH('Moreniko$hikitico2026', 'SHA256'), 10);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('HV02-242V', 'root', STANDARD_HASH('Moreniko$hikitico2026', 'SHA256'), 11);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('FILER01-242V', 'root', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 5);
INSERT INTO USUARIOS_CREDENCIALES (AMBITO, USUARIO, PASSWORD_HASH, ID_EQUIPO) VALUES ('EXTERNA01-242V', 'admin', STANDARD_HASH('Moreniko$hikitico', 'SHA256'), 9);

COMMIT;